apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fun
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: appPOLICY
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
        spec:
          restartPolicy: Never
          containers:
          - name: appNAME
            imagePullPolicy: Always
            image: fun
            resources:
              limits:
                memory: applimitsMEM
              requests:
                cpu: apprequestsCPU
                memory: apprequestsMEM
