apiVersion: apps/v1
kind: Deployment
metadata:
  name: fun
spec:
  replicas: minREPLICAS
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: fun
        image: appIMAGE
        ports:
          - containerPort: appPORT
        resources:
        livenessProbe:
            tcpSocket:
              port: appPORT
            initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: appPORT
          initialDelaySeconds: 2
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 250m
            memory: 250Mi
          resources:
            limits:
              cpu: applimitsCPU
              memory: applimitsMEM
            requests:
              cpu: apprequestsCPU
              memory: apprequestsMEM
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - appNAME
              topologyKey: "kubernetes.io/hostname"
